### ISSUE TITLE
yarn-mistral doesn't work on MacOS

### ISSUE THREAD

**Issue by iddar** [jmorganca/ollama#1012]
I run llama run `yarn-mistral:7b-128k` or `ollama run yarn-mistral` in both times the CLI keep loading infinity.

<img width="691" alt="image" src="https://github.com/jmorganca/ollama/assets/199103/d48cf1e9-694f-4d6f-b88c-342dfa95f333">

In this example I wait over 8 minutes

**Comment by xyproto** [comment]
Could the system be out of memory?

**Comment by iddar** [comment]
maybe, but I use any other model fine

**Comment by mxyng** [comment]
yarn-mistral has a much larger context and a much larger memory footprint than most other models. You may be running out of memory on this along. What are your system specs?

**Comment by easp** [comment]
@iddar What model of Mac? How much RAM?

On my 32GB M1 Max I see similar behavior to what you describe. I checked ~/.ollama/logs/server and it looks like the 128k version is slightly too big and ollama just seems to end up in a zombie state, rather than returning an error. The 64k version loads, but doesn't work very well. Not sure if it's because it isn't trained for chat/instruct, or because of some patches to llama.cpp's YARN support that haven't made it downstream to Ollama yet.

**Comment by iddar** [comment]
I have a 16G of ram

**Comment by igorschlum** [comment]
I have a 32GB macbook M1Pro and it seems to work well.

(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2...   2% |█                                                                                 | (106 MB/4.1 GB, 1.4 MB/s) [1m15s:46m25s]Error: max retries exceeded
(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2...  26% |██████████████████████                                                               | (1.1/4.1 GB, 1.5 MB/s) [13m43s:33m6s]Error: max retries exceeded
(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2...  28% |████████████████████████                                                              | (1.2/4.1 GB, 1.2 MB/s) [1m2s:41m33s]Error: max retries exceeded
(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2...  30% |█████████████████████████                                                             | (1.3/4.1 GB, 1.5 MB/s) [1m5s:32m29s]Error: max retries exceeded
(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2...  63% |█████████████████████████████████████████████████████                                | (2.6/4.1 GB, 1.4 MB/s) [19m5s:17m47s]Error: max retries exceeded
(base) igor@macigor-2 ~ % ollama run yarn-mistral
pulling manifest
pulling 0e8703041ff2... 100% |████████████████████████████████████████████████████████████████████████████████████████| (4.1/4.1 GB, 3.0 MB/s)            
pulling e9d3a814cdd6... 100% |█████████████████████████████████████████████████████████████████████████████████████████████████| (17/17 B,  9 B/s)        
pulling 98e4579df414... 100% |██████████████████████████████████████████████████████████████████████████████████████████████| (307/307 B, 150 B/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
>>> hello, what is yarn-mistral difference over other LLM?
    

1 Like

You should look at this post which explains why mistral was created.
....

**Comment by iddar** [comment]
Thank you very much for the clarification

**Comment by igorschlum** [comment]
Hi @easp,

I've found a solution to the issue you mentioned.

The correct syntax is to omit the quotes around the prompt and keep them only for the path. For example, instead of using:
 
 % ollama run yarn-mistral --verbose "$(cat iliad-book1-21k.txt)" Please summarize the proceeding text
 for a friend who does not have access to it.
 
 In my case I gave the full path of the file :
 
% ollama run llama2 --verbose "$(cat /Users/igor/song.txt)" Please translate in spanish the proceeding text

I hope this helps!
