### ISSUE TITLE
default codellama web server

### ISSUE THREAD

**Issue by kritma** [jmorganca/ollama#1050]
#### `ollama run codellama`, starts web server which listen on port 60263(or dynamic, idk)
* Is this is ok?
* How can i change this port?
<img width="754" alt="image" src="https://github.com/jmorganca/ollama/assets/127416565/d0a688a5-2317-404b-8d71-f9b5b9bdb603">

**Comment by kritma** [comment]
port is dynamic

**Comment by technovangelist** [comment]
We don't start a webserver, with codellama or any other model. I'm not sure what UI that is in the screenshot. Since this issue doesn't appear to be about Ollama, I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
