### ISSUE TITLE
Adding ollama serve to run as a daemon

### ISSUE THREAD

**Issue by rutsam** [jmorganca/ollama#1084]
I have been experimenting with ollama and I noticed it was heavily inspired by docker, however I run it on the server and where I do not use the desktop version, and thus find it better if there were to added an option to **run ollama server as a daemon** in the same fashion as docker compose symbolized with **a parameter -d**

```
ollama serve -d
```

**Comment by Gsvd** [comment]
What operating system are you using?

**Comment by K1ngjulien** [comment]
The standard linux install already sets ollama up as a systemd daemon

https://github.com/jmorganca/ollama/blob/main/docs/linux.md

I'm assuming you're running mac os?

**Comment by technovangelist** [comment]
Looks like this issue is asking about running ollama on a server and that question is resolved in the last comment about running on linux as a daemon. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
