### ISSUE TITLE
how to training my local data use ollama on k8s pod

### ISSUE THREAD

**Issue by xinmans** [jmorganca/ollama#1096]

**Comment by technovangelist** [comment]
So there are a few questions here. First I assume you mean fine tuning rather than training. We don't yet do fine tuning in Ollama, and we are tracking that (because we want to support it) in issue #156. For running ollama in k8s there is an example manifest you can find here: https://github.com/jmorganca/ollama/tree/main/examples/kubernetes. I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
