### ISSUE TITLE
Reduce Embedding size 

### ISSUE THREAD

**Issue by Mohit0928** [jmorganca/ollama#1114]
I'm trying to replicate [this example](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#basic-example) of langchain. I'm using ElasticSearch as the database to store the embedding. In the given example I have replaced `embeddings = OpenAIEmbeddings()` with `oembed = OllamaEmbeddings(model="llama2")` which one can import `from langchain.embeddings import OllamaEmbeddings`. I'm running `Ollama` locally. But, I'm running into below error:
```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'The number of dimensions for field [vector] should be in the range [1, 2048] but was [4096]')
```
The Ollama model always create the embedding of size `4096` even when I sat the chunk size of `500`. Is there any way to reduce the size of embedding?

**Comment by BruceMacD** [comment]
Hi @Mohit0928 the output size of the embedding is determined based on how the model was trained rather than the size of the input, it is a constant. The way to deal with this normally is to use a different model. Ollama doesn't have any embedding specific models in its library at the moment though, so I can't make a great recommendation on a good one to use.
