### ISSUE TITLE
wizard-math:7b terminator not recognized

### ISSUE THREAD

**Issue by Detlev1** [jmorganca/ollama#1123]
I'm using the latest version of Ollama. When using the wizard-math:7b model, the requests don't complete, and instead, a “</s>” terminator is returned. Can I configure the terminator myself to fix this, or is there a way to terminate the request through the API?

**Comment by igorschlum** [comment]
Hello @Detlev1 
I ran the wizard-math:7b model. The model could answer a question, but I have a lot of </s> after the answer.


(base) igor@macigor-2 ~ % ollama run wizard-math:7b
pulling manifest
pulling 66236863bed3... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████▏ (3.8/3.8 GB, 9.6 MB/s)           
pulling 2d836d77287d... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████▏ (61/61 B, 39 B/s)        
pulling 8fadb9ad1206... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏ (106/106 B, 74 B/s)        
pulling 55540d7c14b7... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████▏ (45/45 B, 28 B/s)        
pulling 7deffb4ad549... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████▏ (455/455 B, 281 B/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
>>> What is the velocity of an egg when it hits the ground after falling from a 20-meter high building?
    
The problem is asking for the velocity of an egg when it hits the ground after falling from a height of 20 meters. We can use the following equation to
calculate this:

v = u + at

where:
- v is the final velocity (the velocity of the egg when it hits the ground)
- u is the initial velocity (the velocity just before it was dropped, which is 0 m/s in this case since the egg is not moving initially)
- a is the acceleration due to gravity (which is -9.81 m/s² because the force acting on the egg is gravity, and its acceleration is -9.81 m/s²)
- t is the time it takes for the egg to fall from the building (20 meters high, so the time taken is 20/9.81 ≈ 2.04 seconds)

Now, let's calculate the final velocity using this equation:

v = 0 + (-9.81) * 2.04
v ≈ -12.24 m/s

The sign of the final velocity is not what you would expect, but remember that the egg breaks upon impact with the ground, so it doesn't actually reach
the ground. The initial upward velocity (u) plus the acceleration due to gravity (a) equals the final downward velocity (-v), so the equation still 
holds true.

Therefore, the velocity of the egg when it hits the ground is approximately -12.24 m/s.

The answer is: 04 seconds)
v = 0 + (-9.81) * 2.04
v ≈ -12.24 m/s
So, the velocity of the egg when it hits the ground is approximately -12.24 m/s.

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

</s>

**Comment by Detlev1** [comment]
That's what I meant. The `< / s >` keep generating continuously. While it's easy to quit in the command line, using the API lacks a similar functionality as far as I know.

**Comment by Detlev1** [comment]
To fix this: /set parameter stop </s>
