### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by shubhammicrosoft1** [jmorganca/ollama#1284]
When i am running a summarization using ollama for reading a 7 MB file & summarizing the data on Linux , it reports 

(bash: /usr/local/bin/ollama: Argument list too long)

Command used 
ollama run llama2 "$(cat data.txt)" please summarize this data

Is this a OS limitation or some configurations that we can update in Ollama

**Comment by BruceMacD** [comment]
This command should work, I did a quick test on Ubuntu to validate. I would guess that there is a character in the file you're opening that is messing with the command input. Maybe try checking for that.

**Comment by easp** [comment]
Trying to feed it a 7MB file sounds problematic.

First, and probably the issue here, `getconf ARG_MAX` will show the maximum command line size in Linux and other POSIX compliant systems. On my linux box its 2MB. Feeding the content via standard input (`ollama run llama2 "please summarize this data" < data.txt`) should get around that, but then you'll run into an even bigger problem.

Second, llama2's context is 4096 tokens. 7MB is going to be a few orders of magnitude more than that. I think the biggest available context in an open source LLM is 200k tokens, which still isn't likely to be enough for 7MB of text.

**Comment by technovangelist** [comment]
It looks like @easp answer addresses your issue. The 7mb file is going to be greater than the context size. 

But I think the error message is a bit cryptic and we should fix that to better point to the actual problem.

**Comment by mxyng** [comment]
The error is from bash, not ollama so there's nothing to be done here. A not-so-recent change also changed the CLI's behaviour to add the contents of stdin to the prompt. An equivalent will be this which won't have the same shell limitations.
```
ollama run llama2 'please summarize this data' <data.txt
```
