### ISSUE TITLE
Need word wrap 

### ISSUE THREAD

**Issue by nathanleclaire** [jmorganca/ollama#150]
<img width="97" alt="image" src="https://github.com/jmorganca/ollama/assets/1476820/fa92e643-a994-46ab-b83c-df3e28fbf758">

It pains me

**Comment by pdevine** [comment]
This is really hard to do because the tokens come back not as complete words but as token fragments. We don't know if the next token is going to be over the size of your terminal or not.

Some thoughts:
  * we could look at the terminal size and if we know the token table we could just wrap if we're under the size of the largest token (I don't know what the size of the largest token is though!)
  * could we just tell the LLM to give back its response with word wrapping?

**Comment by jmorganca** [comment]
Going to close this one for now – we'd love for some richer web or cli clients to support this and would want to avoid too much formatting and stick to the raw terminal emulator. That said if there's an easy way feel free to reopen!

**Comment by mxyng** [comment]
Resolved in #553
