### ISSUE TITLE
When is the Windows Version of Ollama Coming out?

### ISSUE THREAD

**Issue by Arnav3241** [jmorganca/ollama#1548]
Hey there, 
When is the Windows Version of Ollama Coming out?
I am several hundreds of people are waiting for it eagerly including since the beginning of this project. Hope to see that update soon as most people use Windows.

**Comment by Titaniumtown** [comment]
Can't you just use WSL? I haven't used windows in a little over a decade now, wouldn't that work?

**Comment by mongolu** [comment]
It works, and it works very well.
🥂👍😀

**Comment by easp** [comment]
I don't know the answer, but I think they are working on getting foundations in shape before enabling a new platform.

One thing a maintainer mentioned recently is that they wanted ROCm support before releasing a Windows version since there are so many machines out there with AMD GPUs -- I assume they want people to have a good experience and also not get inundated by half of Windows users complaining about slow text generation performance (probably).

**Comment by technovangelist** [comment]
What @easp said is exactly correct. Issue #403 is probably the best one to watch for this release. I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by Arnav3241** [comment]
I has finally Came, and no i couldnt have used WSL as i had to make an auto py prog with it
