### ISSUE TITLE
Where are the models pulled to?  

### ISSUE THREAD

**Issue by m3kwong** [jmorganca/ollama#155]
It downloaded 7 gigs of stuff and i can't seem to find where it went.  I want to download it.  Any ideas?

**Comment by mchiang0610** [comment]
@m3kwong We store the models in layers in `~/.ollama/models`.

If you list that folder, you'll see two directories: **blobs** and **manifests**. Blob is the raw data, and manifest is the metadata. Together, they make up the model. 

If you are looking for a model file (e.g. .bin file), it's currently not available. We can look into potentially building an export feature for the file.

**Comment by abulka** [comment]
If you don't have much storage on your main mac drive and keep big files on an external drive, you can use a symbolic link to trick ollama into putting the files on an external drive.

```
# move existing models
mv ~/.ollama/models /Volumes/SSD/Data/ollama/models
# or before you start
mkdir -p /Volumes/SSD/Data/ollama/models

ln -s /Volumes/SSD/Data/ollama/models ~/.ollama/models
```

**Comment by jmorganca** [comment]
Closing as this question has been answered. Moedls are pulled to:

```
~/.ollama/models
```

Note they are stored as blobs so they can be re-used between models that share different prompts, etc.

**Comment by Nasreddine** [comment]
I cannot locate the model directory in the specified location, "~/.ollama/models," on Linux!

**Comment by byteconcepts** [comment]
If ollama is installed by root on a linux system like it should be because it is installing a system-service, models etc are stored under /usr/share/ollama/.ollama.

The directory /usr/share/ollama is used as the home directory for the system-user ollama which is added to the OS for running the systemd system-service.

A normal user does not have access to this dir because it is owned by the ollama user.
If you like another normal user have read access to ollama home directory, you need to add this user to the ollama usergroup.

But a normal user can use the ollama console application to access the ollama system-service!

**Comment by insooneelife** [comment]
where is the model directory in windows?

**Comment by oricoh** [comment]
can't you put them in folders under the model name? I want to delete some models but I don't know which is which.

**Comment by NigelWan** [comment]
Win Path：C:\Users\“Username”\.ollama
