### ISSUE TITLE
is ollama server down?

### ISSUE THREAD

**Issue by ralyodio** [jmorganca/ollama#1584]
I've beeing getting "Server connection error" the past few hours with ollama-webui

**Comment by justinh-rahb** [comment]
It's got nothing to do with this project.

**Comment by igorschlum** [comment]
@ralyodio thank you for sharing ollama-webui. I played with it and it's a nice interface for Ollama on the browser.
I went in the settings and changed /ollama/api to /ollama/api2 and I got the "Server connection error" message. Therefore, I think that this message is related to the settings of your computer rather than the ollama server.
If you agree on this and resolved the issue, you can close it so we can stay under 300 open issues.

**Comment by rgaidot** [comment]
the endpoint `/ollama/api2 `doesn't exist, why and where use this endpoint?

**Comment by ralyodio** [comment]
i am running nginx proxy instead of it and mapped /ollama/api to localhost:11434/ollama/api but that didn't work either

**Comment by rgaidot** [comment]
maybe you should check nginx to set X-Forwarded-<*>, X-Remote-Addr, proxy_set_header, etc... on nginx

**Comment by ralyodio** [comment]
I got it working by changing the fallback port to my proxied port

**Comment by igorschlum** [comment]
Hii @rgaidot I put /ollama/api2 to show the that the message "Server connection error" is not in Ollama website server, but a configuration problem in the computer hosting Ollama.
