### ISSUE TITLE
ollama models corrupted?

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1586]
I've noticed that after running a few models, sometimes the models don't behave normally.  This is a session where that was occurring. I had first tried with bakllava but it wasn't being helpful either. But notice that after I did the systemctl restart ollama the results were much better.

Is something being corrupted in memory? I'll do what I can to help debug this.

```
ollama run llava
>>> look at ./classic.jpg
Added image './classic.jpg'



>>> what is it?




>>> what is ./classic.jpg
Added image './classic.jpg'




>>> hello





>>> /bye
chris@FORGE:~/ai/aiprojects/OllamaPlayground/createnotes$ systemctl restart ollama
chris@FORGE:~/ai/aiprojects/OllamaPlayground/createnotes$ ollama run llava
>>> look at ./classic.jpg
Added image './classic.jpg'
1. The Underwood typewriter is an old fashioned machine that appears to be made of wood and metal components.
2. It has a black keyboard with silver numbers on the side, giving it a vintage appearance.
3. There are several keys visible, including letters such as A, B, C, D, E, F, G, H, I, J, K, L, M and N along with numeric keys 1 through 9.
4. The typewriter sits on a table and is placed underneath the desk.

```

**Comment by igorschlum** [comment]
hi @iplayfast 

I played and if you add image in your prompt, it's working well without restarting Ollama neither llava

>>> what is ./image.png
Added image './image.png'



>>> look at ./image.png
Added image './image.png'
4:01:37 PM

>>> what is the size of ./image.png
Added image './image.png'
50,000 bytes

>>> what is the size of this picture ./image.png
Added image './image.png'
1024x768

>>> look at ./image.png
Added image './image.png'
6

>>> 
(base) igor@MacStudiodeIgor ~ % look at ./image.png
(base) igor@MacStudiodeIgor ~ % ollama run llava
>>> look at ./image.png
Added image './image.png'
10:54 AM

>>> describe ./image.png
Added image './image.png'
1. You

>>> describe: ./image.png
Added image './image.png'
1. The main class is "class AdminPanelProvider".
2. The code is written in C++ language.

>>> describe: /Users/igor/image.png 
Added image '/Users/igor/image.png'

COLOR: Blue

>>> describe this image: /Users/igor/image.png 
Added image '/Users/igor/image.png'

I see a large amount of computer code, which is being displayed on a black
background. The code appears to be written in a purple and yellow color 
scheme, with multiple colors filling the screen. The code appears to be 
written in C++ programming language, and it has a specific focus on the 
administration panel. There are several instances of the word "panel" 
throughout the code, indicating that this is a key element within the 
program.

>>> describe this image ./image.png
Added image './image.png'

The image is a close-up of code in black and purple, likely written using 
Python. The code appears to be related to an email system, with sections 
such as the "app" and "page" parts being prominent features. There are 
also lines for the "frame" and "data" components within this programming 
setup.

**Comment by iplayfast** [comment]
No, I've been adding images. It seems to be a corruption that accumulates over time, on the server. 
The code at https://github.com/iplayfast/OllamaPlayground/tree/main/createnotes goes through all models and asks questions of them. By the time it gets to the end of the list the Ollama server is pretty much braindead.

**Comment by igorschlum** [comment]
@iplayfast I will try to run your script on a MacStation with lot of memory and see if I can reproduce the problem.

**Comment by iplayfast** [comment]
close issue as it is covered elsewhere

**Comment by igorschlum** [comment]
@iplayfast I could run your script createnotes on my Mac and Ollama stop working and my fan is on since.
Ollama is taking 97,8% of the GPU. I will test again with Ollama 0.1.18 when released to see if the issue is resolve


(modelnotes) igor@macigor-2 createnotes % python CreateNotes.py
Attempting to load each model to see if they can be loaded
   attempting to load model codellama:34b
         model codellama:34b loaded in 34.7 seconds
   attempting to load model codellama:latest
         model codellama:latest loaded in 7.9 seconds
   attempting to load model deepseek-coder:6.7b-base-q5_K_M
         model deepseek-coder:6.7b-base-q5_K_M loaded in 38.9 seconds
   attempting to load model deepseek-coder:latest
         model deepseek-coder:latest loaded in 2.4 seconds
   attempting to load model dolphin-phi:latest
         model dolphin-phi:latest loaded in 3.4 seconds
   attempting to load model falcon:latest
         model falcon:latest loaded in 7.6 seconds
   attempting to load model llama2:13b
         model llama2:13b loaded in 16.1 seconds
   attempting to load model llama2:latest
         model llama2:latest loaded in 7.0 seconds
   attempting to load model llama2-uncensored:latest
         model llama2-uncensored:latest loaded in 6.7 seconds
   attempting to load model llava:13b
         model llava:13b loaded in 14.0 seconds
   attempting to load model llava:latest
         model llava:latest loaded in 9.7 seconds
   attempting to load model medllama2:latest
         model medllama2:latest loaded in 7.7 seconds
   attempting to load model mistral:latest
         model mistral:latest loaded in 7.5 seconds
   attempting to load model neural-chat:latest
         model neural-chat:latest loaded in 7.8 seconds
   attempting to load model orca2:13b
         model orca2:13b loaded in 15.8 seconds
   attempting to load model stablelm-zephyr:3b-q6_K
         model stablelm-zephyr:3b-q6_K loaded in 6.3 seconds
   attempting to load model starling-lm:latest
         model starling-lm:latest loaded in 8.4 seconds
   attempting to load model wizard-math:7b
Timed out after 300 seconds for question: are you there
