### ISSUE TITLE
Access internet

### ISSUE THREAD

**Issue by PeachesMLG** [jmorganca/ollama#1589]
Im customising my own model, using the steps in the ReadMe.

In this Modelfile I added a link to an faq with a bunch of information available, aswell as a github url in hopes it can search open/closed issues to awnser queries.

However it doesnt seem to be querying the url's like OpenAI GPT4 does

Is this currently possible?

**Comment by technovangelist** [comment]
Hi @PeachesMLG 

Thanks so much for submitting this issue. Models never have access to the outside world. Whenever you see a service that seems to give access to the outside world to a model, a developer has done some sort of search for relevant info, then sent that to the model for evaluation. And the same goes for us. There are a number of projects that you can find at the bottom of the readme on the repo that discuss RAG, or you can try to develop a solution yourself. Thanks again and let us know if you find anything else missing.

**Comment by Danzelite** [comment]
Hey idk if anyone will see this but due to the new release of the python/javascript library you can connect models to the web here is an example of a wiki-chatbot I made using the wiki-library for python and the ollama-python library:

import wikipedia, ollama

user_input = input("")

context = wikipedia.summary(user_input)

response = ollama.chat(model='qwen:0.5b', messages=[
  {
    'role': 'user',
    'content': context,
  },
])
print(response['message']['content'])

**Comment by areyoufeelingitnowmrkrebs** [comment]
> Hey idk if anyone will see this but due to the new release of the python/javascript library you can connect models to the web here is an example of a wiki-chatbot I made using the wiki-library for python and the ollama-python library:
> 
> import wikipedia, ollama
> 
> user_input = input("")
> 
> context = wikipedia.summary(user_input)
> 
> response = ollama.chat(model='qwen:0.5b', messages=[ { 'role': 'user', 'content': context, }, ]) print(response['message']['content'])

How do you use this to connect a model to the internet? I'm using phi4 on Arch.
