### ISSUE TITLE
Discord management

### ISSUE THREAD

**Issue by Luxadevi** [jmorganca/ollama#1611]
A lot of users are complaining about the usability of the Ollama Discord.

There is only one channel, and with the growing userbase, it will sometimes be impossible to converse or help other users with issues.

So, I wanted to propose making some varied channels for different use cases. A couple of examples are:

- General
- Model Discussion
- API Discussion
- Integrations
- Model File/Configuration Sharing
- Help/Support Channel
- Off-topic

These are just a few examples, depending on the needs and ideas from the community.

Also, it would be a good idea to have some sort of moderation team and rules on the Discord about what users are allowed to discuss.

I also want to offer myself up to make/implement these changes and be part of moderation.

My discord username is luxaplexx, you probably seen me around :)

**Comment by mchiang0610** [comment]
Hi @Luxadevi, thank you so much for bringing this up. All the maintainers really like candid feedback to help us improve Ollama. 

In terms of creating multiple channels on Discord, we are very particular with it because it's meant to be a place for the community to gather in the same place akin to being in the same room. We try hard to make it mimic the experience of being in person attending one of our community meetups with people (both users and non-ollama users) in the same room. 

Now, this might look really messy in the beginning but it allows people to easily overhear others, and creates spontaneous discussions. 

For very serious topics, we've had many private discussions via Discord. Or if very focused on an individual topic, we have had some members create discord threads. 

I could be very wrong about how we should be thinking about this, and ultimately should change for the community to be better. So far it actually seems to create better engagement with our users on Discord. 

We made our first step by turning off the welcome messages of individuals joining. 

Thank you! We do try to keep a good eye on Discord but obviously rely on the community to continuously improve our Discord. 

Again, thank you for bringing this up and being candid about it. I'm sure I will come back and revisit this one day. 

Thanks! I'm going to close this issue for now, but feel free to ping me on Discord as mchiang or michael@ollama.ai
