### ISSUE TITLE
How to skip animation?

### ISSUE THREAD

**Issue by kokizzu** [jmorganca/ollama#1616]
for example when i run:
```
ollama run mistral 
>>> some prompt

... very slow letter by letter output ... <-- how to make this faster?

```

**Comment by igorschlum** [comment]
hi @kokizzu it's like that when there is not enough available memory. If you are on a Mac with 8GB of RAM, try to restart and only launch Ollama and Terminal. It could be faster, buy 8GB is not enough for Mistral.

**Comment by pdevine** [comment]
@kokizzu what are the specs for your system? If you have a limited amount of GPU memory this would be expected behaviour.

**Comment by kokizzu** [comment]
32 core Ryzen 9 , 128GB '__') but no nvidia GPU, just old AMD RX 6600 XT

**Comment by pdevine** [comment]
Unfortunately you are running on the CPU and it's just not very fast. The AMD support is *just* about to go in, but I'm not sure if that card is supported in ROCm 6. You can try it w/ PR #1146 or wait until that gets merged (hopefully later today or tomorrow).

If you are using the API (either `/api/generate` or `/api/chat`) you can set `stream=false` which will return everything as one response instead of token by token, but there isn't a way to do that in the REPL (i.e. the CLI).

Barring that, you can either try by renting an instance in the cloud (like on Fly.io or from Paperspace), or upgrade to a faster system. I'm going to go ahead and close the issue, but feel free to re-open it (or better, just ask on the discord) if you want to follow up.
