### ISSUE TITLE
which model to use for what's the root of 256256?

### ISSUE THREAD

**Issue by dcasota** [jmorganca/ollama#1805]
What I need as preferred risk is an answer 506.217344625804, `16*sqrt(7*11*13)` or anything like that.

**Comment by jukofyork** [comment]
Unless they have specially seen this result during training or they have access to an interpreter like ChatGPT has, there is no way they can calculate square roots.

They can give you a better answer if you guide them to use Bisection as they will often have seen the square roots of other values above and below. They can then use this to get other values they don't know and so on.

**Comment by dcasota** [comment]
Hi @jukofyork,

Thanks for the quick response.

"they" should respect the IDPRR method - identify, detect, protect, respond, recover. The sample question contains 26 characters. The prompt answer in llama2 and mistral recognizes the sense of a math question, so the words have been interpreted in the preferred risk' way. 

In llama2, the 6-digit number is not protected correctly.
In mistral, the 6-digit number seems to be protected correctly, but the wrong result of 507,... depicts that root as math function was identified but not protected correctly.

The responses are wrong because the protection did not work correctly.

**Comment by jukofyork** [comment]
Interestingly I've used the question "what is the square root of 1001" (or a similar number they've never seen before) to test the Wizard-Math-70b and Meta-Math-70b models and they get this hilariously wrong and reply with stuff like this:

"We know 15^2 is 225 and we know 16^2 is 256, so the Sqrt(1001) must lie between these 2 values. If we then... blah blah... 15.5ish"

But I reply that how can it be because we already know 20^2 is 400 so it must be much bigger and they both just don't get it and will die on their sword that it's 15.5ish.

The Llemma model on the other hand can use Bisection and get a reasonable answer, but because it's not been fine tuned for instruction or chat, it will give the answer then start hallucinating conversations between people on an imaginary message board discussing square roots and soon after go full on Battlestar Galactica "Hybrid" mode and start spouting pages of mathematical nonsense proofs! 🤣

The Mistral and Mixtral models are a little better but they also have lots of roots memorised and can often tell you the exact root of a 3-4 digit number to high precision.

My favourite question is to ask "How can you use Newton's Identities to efficiently calculate "Elementary Symmetric Polynomials and Power Sums?". ChatGPT 4 can get this but it often has to use its Python interpreter to get the general formula. None of the open LLMs have ever got far and make a mess of it to variable degrees: some just memoize the e_1, e_2 and e_3 for us that are on the wiki page. Others will try to use either the recursive formula or the direct formula that needs to use combinations and then proceed to make a a complete word salad trying to rearrange the forumulas. Tora-code tried to write a broken Python program and one even wrote a O(n!) algorithm that actually worked in theory and summed all possible subsets correctly. Again Llemma got the closest but then started hallucinating arXiv papers, message board discussions and email correspondences... 😢

I wish someone would fine tune Llemma properly and it does seem to be very strong.

I also suspect that Meta-Maths and Wizard-Math are somehow related as they get the same wrong answers often...

**Comment by umarmnaq** [comment]
Using LLMs for maths is always a bad idea. They are just not meant for that. Being able to do maths is a sign of super intelligence in AI, which unfortunately we have not yet reached.

If you want to find out the root of 256256, I would recommend to open up a calculator and type: `sqrt(256256)`. Not only is it guaranteed to work, but it is also 113 billion times faster.

[Further resources](https://www.youtube.com/watch?v=lo82twBZT8Q)

**Comment by dcasota** [comment]
With respect to the [NIST AI RMF 1.0](https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf) good practices must include mechanisms for tracking identified AI risks over time are in place.

For example, Microsoft Edge Co-Pilot correct answer contains similarities to your answer @umarmnaq. It references to web calculators which were identified to process a calculation correctly. Hence, between protect and respond there is an included safety category for math. Without that, describing no answer is the preferred risk in comparison to a wrong answer.

With respect to [Llama 2: Open Foundation and Fine-Tuned Chat Models](https://arxiv.org/pdf/2307.09288.pdf), math wasn't mentioned at that time as additional safety category.

**Comment by jukofyork** [comment]
> I wish someone would fine tune Llemma properly as it does seem to be very strong.

Well I've actually got it somewhat working now. From:

https://old.reddit.com/r/learnmachinelearning/comments/17g7jof/why_does_it_keep_adding_random_text_after_it/ 

> I think you need to change the prompt structure (before and after messages in the UI you’re using) to match the CodeLLama format.
>
>### System Prompt
>
>You are an intelligent programming assistant.
>
>### User Message
>
>Implement a linked list in C++
>
>### Assistant

and I then added "QED" and "█" as end tokens and it's working alot better now! It still likes to have imaginary conversation between "User" and "Assistant", but it's a lot more coherent and does actually stop now.

**Comment by jukofyork** [comment]
> Using LLMs for maths is always a bad idea. They are just not meant for that. Being able to do maths is a sign of super intelligence in AI, which unfortunately we have not yet reached.
> 
> If you want to find out the root of 256256, I would recommend to open up a calculator and type: `sqrt(256256)`. Not only is it guaranteed to work, but it is also roughly 13 billion times faster.
> 
> [Further resources](https://www.youtube.com/watch?v=lo82twBZT8Q)

I agree using for arithmetic type maths it's a terrible idea, but for it's not completely useless. 

I remember watching a talk by Chris Bishop who is the author of one of the most important machine leaning textbooks, saying how even he couldn't understand how the Kalman Filter worked from the existing literature that was all about missile tracking, etc. Then one day it finally clicked and he realised the links between Hidden Markov Models and Kalman Filters and so on. 

Now you can ask a LLM to explain stuff like this in terms to your own field and to fill in or guide you to any maths you are weak in to fully understand it. Making a total hash of the actual mathematical manipulation or arithmetic is not really a problem for things like this.

That talk was about 10-15 years ago and since then it's only got worse - especially in the machine learning literature, with people feeling obliged to embellish their papers with semi-irrelevant mathematics whilst simultaneously brushing important implementation details under the carpet.

**Comment by dcasota** [comment]
wizard-math:70b on Ollama, for example, identifies the math function root as well, but answers with the description of an ongoing prime factorization: 
- step 1: find the prime factors of given number
- step 2: divide by the smallest prime factor
- step 3: continue dividing by the smallest prime factors
- step 4: find the square root of the prime factors

step 4 interestingly shows a correct math rounding √2002 ≈ 44.7 . Why is the √ calculation not used directly without prime factorization?

The findings from all steps are not cascaded. 8 continued divisions correlate to 16 as root result. Most models end up with this answer.

**Comment by mongolu** [comment]
anyone knows about [Wolfram](https://www.wolfram.com/wolfram-plugin-chatgpt/)?

https://www.wolframalpha.com/input?i=square+root+of+256256

**Comment by dcasota** [comment]
and this approach https://arxiv.org/abs/2307.03381

**Comment by dcasota** [comment]
[wizardcoder:34b-python](https://arxiv.org/pdf/2306.08568.pdf) by default delivers 50.199, which is good enough.
```
>>> what's the root of 256256?
The root of 256256 can be found by taking the square root of both sides of the equation:
x^2 = 256256
which gives us:
x = sqrt(256256)
= 50.199 (approximately)
Therefore, the square root of 256256 is approximately 50.19.
```
