### ISSUE TITLE
Cuda Error with 2GB VRAM: `Error: Post "http://127.0.0.1:11434/api/generate": EOF` 

### ISSUE THREAD

**Issue by falaimo** [jmorganca/ollama#1838]
Hello everyone, in Ollama version 0.1.18, I'm encountering the error "Error: Post "http://127.0.0.1:11434/api/generate": EOF" when starting Ollama with any model. I think it depends of cuda...
[logs_ollama.txt](https://github.com/jmorganca/ollama/files/13852832/logs_ollama.txt)

**Comment by pierreuuuuu** [comment]
Hello, I was about to create a ticket as well, I have the same behavior, the same error message about cuda:
"GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:7801: !"CUDA error""
I don't if it has a link to the error, but I have the same gpu as you, geforce gtx 950m.
I'm using also ollama v0.1.18, on ubuntu 22.04.3, and I'm trying to use mistral "ollama run mistral".

I've read older posts about "Error: Post "http://127.0.0.1:11434/api/generate": EOF", and the answer was about not enough ram memory, but I have 16GB and I thought it was enough for mistral.

[logs.txt](https://github.com/jmorganca/ollama/files/13852949/logs.txt)

Any ideas ?
Thanks for reading

**Comment by kursatgormez** [comment]
I got same error after update ollama.

**Comment by jmorganca** [comment]
Hi all, sorry you hit this error. Working on a fix! 

Here's a handy one line script for installing the previous version (which would fallback to CPU-only) until this is fixed

```
curl https://ollama.ai/install.sh | sed 's#https://ollama.ai/download#https://github.com/jmorganca/ollama/releases/download/v0.1.17#' | sh
```

**Comment by kursatgormez** [comment]
My machine is Macbook Pro M2.

**Comment by jmorganca** [comment]
@kursatgormez sorry about that – would it be possible to share any error you might see in the logs? `~/.ollama/logs/server.log`

Thanks so much

**Comment by kursatgormez** [comment]
My main purpose is fine-tuning llama2. So, I used llama.cpp for crate gguf file then insert with ADAPTER.
Maybe the GGUF file did this.
I lost my server.log, but if i face this situation i will ask. thank you so much

**Comment by deltawi** [comment]
Hey team, I am facing the same issue on `Ubuntu 22.04` with `GPU RTX A5000`. I am trying the `mixtral:8x7b-instruct-v0.1-q4_0`.

**Comment by Cybervet** [comment]
I think the problem continues , at least when we compile from source. Here is a the error msg when trying to run a small model in a 2 g VRAM . After the cuda error instead of falling in CPU only mode it exits.


2024/01/08 17:39:36 routes.go:930: Listening on 127.0.0.1:11434 (version 0.0.0)
2024/01/08 17:39:42 shim_ext_server.go:142: Dynamic LLM variants [cuda]
2024/01/08 17:39:42 gpu.go:37: Detecting GPU type
2024/01/08 17:39:42 gpu.go:56: Nvidia GPU detected
2024/01/08 17:39:42 gpu.go:86: CUDA Compute Capability detected: 5.0


llm_load_tensors: ggml ctx size =    0.08 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   35.52 MiB
llm_load_tensors: offloading 24 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 25/25 layers to GPU
llm_load_tensors: VRAM used: 703.44 MiB
...........................................................................................
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: freq_base  = 100000.0
llama_new_context_with_model: freq_scale = 0.25

CUDA error 2 at /root/ollama/llm/llama.cpp/ggml-cuda.cu:9132: out of memory
current device: 0
GGML_ASSERT: /root/ollama/llm/llama.cpp/ggml-cuda.cu:9132: !"CUDA error"
SIGABRT: abort
PC=0x7fd38b6a9d3c m=4 sigcode=18446744073709551610
signal arrived during cgo execution
