### ISSUE TITLE
Ability to download LLAMA2 70b

### ISSUE THREAD

**Issue by plannaAlain** [jmorganca/ollama#193]

**Comment by XBeg9** [comment]
Any workarounds to download 70b model?

**Comment by BruceMacD** [comment]
We will add this, as a workaround in the meantime you could try downloading a binary file from huggingface and running it with a Modelfile.

(this is untested, because I can't run a 70B model at the moment)
1. Download a 70B binary (ex: [llama-2-70b.ggmlv3.q4_0.bin](https://huggingface.co/TheBloke/Llama-2-70B-GGML/blob/main/llama-2-70b.ggmlv3.q4_0.bin))

https://huggingface.co/TheBloke/Llama-2-70B-GGML/tree/main

2. Create a Modelfile:
```
FROM ./BIN_FILE_LOCATION

TEMPLATE """
{{- if .First }}
<<SYS>>
{{ .System }}
<</SYS>>
{{- end }}

[INST] {{ .Prompt }} [/INST]
"""

SYSTEM """
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
"""
```

3. In a terminal run: `ollama create NAME -f ./Modelfile`

4. `ollama run NAME`

**Comment by jvence** [comment]
Tried following @BruceMacD 's instruction but I get an error saying:
`>>> hello
Error: failed to load model`

**Comment by burggraf** [comment]
I tried running `ollama run llama2:70b` and while it did seem to download successfully, I also got the same error: `Error: failed to load model`.

**Comment by mxyng** [comment]
The 70b chat and non-chat models are available for download under the tags `llama2:70b-chat-q4_0` and `llama2:70b-q4_0`. Other quantization levels such as K-quants are available as well. Here's a full list of the available models:

```
llama2:70b-chat-q3_K_L
llama2:70b-chat-q3_K_M
llama2:70b-chat-q3_K_S
llama2:70b-chat-q4_0
llama2:70b-chat-q4_1
llama2:70b-chat-q4_K_M
llama2:70b-chat-q4_K_S
llama2:70b-chat-q5_K_M
llama2:70b-chat-q5_K_S
llama2:70b-q2_K
llama2:70b-q3_K_L
llama2:70b-q3_K_M
llama2:70b-q3_K_S
llama2:70b-q4_0
llama2:70b-q4_1
llama2:70b-q4_K_M
llama2:70b-q4_K_S
llama2:70b-q5_K_M
```

**Comment by jvence** [comment]
This is not working:
 
ollama run llama2:70b-chat-q4_0
>>> hello
Error: failed to load model
