### ISSUE TITLE
Cloud storage support

### ISSUE THREAD

**Issue by beliboba** [jmorganca/ollama#1976]
Is there any support for cloud storage for models? If no, will it be ever implemented?

**Comment by easp** [comment]
What are you wanting, exactly? Do you want to store private models in the cloud and have Ollama retrieve them automatically?

**Comment by beliboba** [comment]
I see it like this
I have a cloud storage with ftp access or some other method, and ability to set it somewhere in config so Ollama can retrieve my models from there

**Comment by pdevine** [comment]
Hey @beliboba , you can already do this right now. Go to `https://ollama.ai/signup` and create an account. You can then go to `https://ollama.ai/settings/keys` when you're signed in and upload your ollama public key (on macos it's in `~/.ollama/id_ed25519.pub`).

If you then create a model called something like `<yournamespace>/<yourmodel>` you can push it to ollama using `ollama push <yournamespace>/<yourmodel>`.

**Comment by beliboba** [comment]
So i wouldnt need to download them?

**Comment by pdevine** [comment]
I think I misinterpreted what your request was. Are you asking to store all of your models in the cloud and then run then from there (but on your local machine)? Or do you mean you want to save a model that you made to the cloud and be able to pull it?

The first use case wouldn't work very well, because you'd have to download the weights every time you wanted to run a model. Unless you had a lot of bandwidth, that wouldn't really be feasible. You could do it though with NFS or some other protocol and then use the `OLLAMA_MODELS` environment variable when you start `ollama serve` to change the location of your models. So it could work, but it won't be very performant.

For the second use case, you can do that with what I was describing earlier. You would still need to `ollama pull` the models before using them.
