### ISSUE TITLE
What quantization is used to quantize Phi-2?

### ISSUE THREAD

**Issue by bm777** [jmorganca/ollama#2046]
Running Phi-2 with Ollama is faster than running Phi-2 in Rust with Candle. rust is taking 1.7 GB of my memory while Ollama only 788MB of memory. I guess it is using the same GGUF quantized 1.6 Gb

Ollama is 
 - quantizing it at run time or 
 - it does it before hand
 - or using lama.cpp under the hood
 - no quantization at all.
----

**Comment by easp** [comment]
Look at https://ollama.ai/library/phi/tags. You can check the fingerprint to figure out which quantization is used for phi:latest. Or not, because at this point you can pretty much count on it being q4_0 for any model in the ollama.ai/library.

That said, your memory utilization figure probably off for Ollama. It uses llama.cpp under the hood and mmaps the model weights. This doesn't show up as part of the processes memory. Instead it's accounted for under the file cache on linux and either wired memory (when an inference is in progress), or file cache (when idle) on MacOS.
