### ISSUE TITLE
Overwriting an existing model from a modelfile leaves old blob not deleted

### ISSUE THREAD

**Issue by hyjwei** [jmorganca/ollama#2097]
### Problem ###
When I import a GGUF model into ollama, I create a modelfile with "FROM" line and then run `ollama create`, and a blob is created in model directory.

Then I decide to import another GGUF model (different quant parameters), I modify the "FROM" line and the run `ollama create` again. A new blob is created, but the old blob is still in model directory.

If I run `ollama rm` to remove the model, only the second blob is deleted but the old one is still there. I don't know how to properly delete that old blob using ollama command line and I have to delete the file manually.

### Expected behavior ###

When I overwrite a existing model using `ollama create` command, the old blobs should be removed.

Or, there should be an option, like `fsck`, to purge the obsolete blobs from model directory.

Regards,

**Comment by mxyng** [comment]
This is somewhat intentional. When creating a model, ollama doesn't check if it's overwriting an existing model. Therefore replacing an ollama model with a different binary model will seem as two separate, unrelated creates

> Or, there should be an option, like fsck, to purge the obsolete blobs from model directory.

A full directory scan happens when ollama server starts. It will detect any dangling blobs and remove them
