### ISSUE TITLE
Why does the app add itself to the "Open at Login" items on Mac?

### ISSUE THREAD

**Issue by 1234igor** [jmorganca/ollama#240]

**Comment by jmorganca** [comment]
Hi @1234igor, thanks for creating an issue! Since Ollama is a long running api server (similar to `docker` and some other tools), it starts in the background so you can run `ollama` without first thinking to have to start the app. It's surprisingly common to forget to start it before running CLI commands. (Also note #47 which will help this issue).

That may not be your cup of tea (totally understand) – you can disable it in the system preferences, or if you prefer to opt out of the macOS app for now altogether, it's easy to [build the binary](https://github.com/jmorganca/ollama#building). Binaries are also published with [every release](https://github.com/jmorganca/ollama/releases/tag/v0.0.12) – note: the next version will include a signed macOS `universal` binary!

**Comment by 1234igor** [comment]
Thanks a lot for your answer!

**Comment by jmorganca** [comment]
You got it! Will close this as #47 is open, and stay tuned for the next release!

**Comment by dbarros** [comment]
This should be an opt-in setting, as the user should have control of their computer and apps. Yes, I can remove it from Settings' Login items, but every time I run Ollama it adds itself back in to that list.
