### ISSUE TITLE
Ollama running in Dockerfile

### ISSUE THREAD

**Issue by osamanatouf2** [jmorganca/ollama#258]
@jmorganca @mxyng I got ./ollama serve to work in docker. The only issue is that I am not able to pull down the files for other models like llama2 via the commad ./ollama pull llama2. I have tested the same configuration on ubuntu and works fine. Just inside the docker I get the following issue: ```Error: Post "http://127.0.0.1:11434/api/pull": dial tcp 127.0.0.1:11434: connect: connection refused```
Here is my Dockerfile: 
```
ROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y git

WORKDIR /home

RUN (cd /home; git clone https://github.com/jmorganca/ollama.git)
RUN apt-get install -y wget
RUN wget https://golang.org/dl/go1.20.7.linux-amd64.tar.gz -O go.tar.gz
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN tar -C /usr/local -xzf go.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
RUN go version
RUN rm go.tar.gz
WORKDIR /home/ollama
RUN go build .
RUN ./ollama pull llama2
EXPOSE 11434
RUN ./ollama serve &
```
and it only fails on the line RUN ./ollama pull llama2 and I have no clue where the issue is coming from:

**Comment by BruceMacD** [comment]
The issue here is that the ollama CLI sends a pull request to the server, so in this case when `ollama pull llama2` is run it fails because `ollama serve` hasn't been run yet to start the server. 

Maybe this will work:
```
FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y git

WORKDIR /home

RUN (cd /home; git clone https://github.com/jmorganca/ollama.git)
RUN apt-get install -y wget
RUN wget https://golang.org/dl/go1.20.7.linux-amd64.tar.gz -O go.tar.gz
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN tar -C /usr/local -xzf go.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
RUN go version
RUN rm go.tar.gz
WORKDIR /home/ollama
RUN go build .
EXPOSE 11434
RUN ./ollama serve &
RUN ./ollama pull llama2
```

**Comment by osamanatouf2** [comment]
@BruceMacD Does not seem to be the issue. Were you successful in running the build?

**Comment by mxyng** [comment]
There's a fundamental problem with this Dockerfile. It's not good practice to run background processes like since a Dockerfile is a recipe to generating a Docker image and is not equivalent to the runtime of the container.

An example Dockerfile exists in the repo. This give you a container that runs `ollama serve` by default:

```
docker build -t ollama -f Dockerfile .
docker run -d -p 11434:11434 -v $HOME/.ollama:/home/ollama/.ollama ollama
ollama pull llama2
```

@osamanatouf2 can you elaborate on what you're trying to achieve so we can understand the problem?

**Comment by osamanatouf2** [comment]
@mxyng I am trying to get ollama as a stand-alone service that we ship with a docker container and integrate it into another library promptstool library in this case.  ollama does not work across all systems and that is the reason why I choose docker. I got it working on Ubuntu locally, but does not seem to be working in Dockerfile env.

**Comment by mxyng** [comment]
I see. In that case you have two options:

1. Build a Docker image using the Dockerfile in the repo as a starting point and `COPY` in a local model. Keep in mind `docker build` can only `COPY` files in its context so you'll need to link `~/.ollama/models` to your `docker build` context. This creates a large container (GBs) where both `ollama server` and `llama2` exist in a single Docker image.
2. Build a Docker image using the Dockerfile in the repo and integrate it into your library. At runtime, configure the model which will pull it from the registry. The container will be small but the end user will still need to pull the image.

There's no functional difference between either methods. Either way, the end user will need to pull both ollama and model.

I suggest option 2 because the container can be reused for other models, i.e. if the end user wants to use something other than llama2.

**Comment by jmorganca** [comment]
Hi @osamanatouf2 @steventkrawczyk 

As @mxyng mentioned there's a `Dockerfile` in this repo that's a great starting point: https://github.com/jmorganca/ollama/blob/main/Dockerfile

With this you can run Ollama in a container:

```
docker build . -t example
docker run -p 111434:111434 example
```

From there you'll be able to connect to it to pull a model and run it!

```
curl -X POST http://localhost:11434/api/pull -d '{"name": "llama2"}'
curl -X POST http://localhost:11434/api/generate -d '{"model": "llama2", "prompt":"Why is the sky blue?"}'
```

Would this solve your problem?

**Comment by jmorganca** [comment]
To add: generating in Docker may not always be the best option because of performance.

For example on Mac, the virtualization framework (where Docker runs) unfortunately does not support GPU acceleration. How are you looking to run Ollama so that it works with `prompttools` on all platforms?

**Comment by jmorganca** [comment]
Checking in here folks! @osamanatouf2 @steventkrawczyk how is the integration with Ollama coming along? We're you able to get up and running? Happy to help :-)

**Comment by osamanatouf2** [comment]
@jmorganca I got ollama working in docker and it is working fine. Just need some extra work to get it ready to use in prompttools repo.

**Comment by priamai** [comment]
I was just fiddling with this, we should also specify which volumes needs to be mounted so that once you download the model and if the container is restarted you don't have to download the models again.

**Comment by priamai** [comment]
Something like this?

```
version: "3.3"
services:
  ollama:
    build:
      context: .
    env_file: .env
    ports:
      - "${HOST_API_PORT:-11434}:${CONTAINER_API_PORT:-11434}"
    stdin_open: true
    tty: true
    volumes:
      - ./models:/app/models
```

**Comment by jmorganca** [comment]
There's now a `Dockerfile` that's kept up to date: https://github.com/jmorganca/ollama/blob/main/Dockerfile

For volumes, you can mount `-v ./ollama:/home/ollama/.ollama` to keep persistence between restarts

Will close this issue for now but feel free to post more or drop in the discord to talk more Docker x Ollama: https://discord.gg/ollama – some of the maintainers are ex-Docker engineers and so we love to chat about this stuff 😊

**Comment by airtonix** [comment]
possibly useful comment in other related ticket: https://github.com/jmorganca/ollama/issues/546#issuecomment-1722759440
