### ISSUE TITLE
Slow performance on Intel CPU

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#275]
When running on an i7-6700K CPU, and 32GB of memory, the performance was very slow

```
ollama run wizard-vicuna --verbose
>>> Hello
    
I hope you're doing well today. May I know your name and purpose of calling?

total duration:       1m57.311123082s
load duration:        3.703261258s
sample count:         21 token(s)
sample duration:      11.928ms
sample rate:          1760.56 tokens/s
prompt eval count:    13 token(s)
prompt eval duration: 44.866549s
prompt eval rate:     0.29 tokens/s
eval count:           20 token(s)
eval duration:        1m8.72493s
eval rate:            0.29 tokens/s
```

**Comment by BSChuang** [comment]
Some additional PC information:
CPU: Intel® Core™ i7-6700 CPU @ 3.40GHz × 8
RAM: 32.0 GiB
GPU: Mesa Intel® HD Graphics 530 (SKL GT2)
OS: Ubuntu 22.04.2 LTS

Our initial guess is the GPU is too poor, but the LLM isn't configured to use GPU (as of yet), and the GPU isn't under any load during evaluation, so that is most likely not the issue.

**Comment by BSChuang** [comment]
I believe the problem is with Ubuntu, I downloaded ollama on windows and have been seeing significant performance increases. I also tested ollama on WSL (also Ubuntu) and saw similar slow performance akin to the initial test.

`./ollama run wizard-vicuna --verbose
>>> hello
Welcome to the chatbot. How may I assist you?

total duration:       9.3766134s
load duration:        1.9104ms
sample count:         14 token(s)
sample duration:      10.419ms
sample rate:          1343.70 tokens/s
prompt eval count:    1 token(s)
eval count:           14 token(s)
eval duration:        9.361045s
eval rate:            1.50 tokens/s`

**Comment by boneitis** [comment]
Nothing substantial to add; just wanted to chime in to say I have sort-of similar hardware and would be happy to help with having tests also run on my hardware.

Don't know if this is to be expected (as I'm pretty new to tinkering with AI chat bots, let alone using them), but I'm getting similar crunch times running up to minutes on my deployment:

llama2-uncensored, 7B
i7-7700 (non-K)
16 GB memory
RTX 2060 12GB (although my understanding is Ollama doesn't tap into GPU)
Mint 22.3 (offshoot of Ubuntu 22 LTS)

I may upgrade to 32 GB if I'm getting enough kicks out of playing with these bots. If it helps with Ollama dev/testing, no problem swapping out models and stuff. For the time being, I intend to leave it running on a fairly active yet casual Discord server I administer.

**Comment by jmorganca** [comment]
Hi folks, this has been open for quite awhile, and there have been quite a few improvements to Ollama's performance – including Nvidia GPU support. I'll close this for now but feel free to re-open if you are still seeing painfully slow responses on modern or semi-modern hardware (<1 t/s)

**Comment by paulwababu** [comment]
I’m still getting similar issues even when running small models like 3B models, I’m using Ubuntu and I have 32 GB of ram on googlecloud

**Comment by uptopoint** [comment]
I am having same problem, i have 3.7Ghz cpu , But Ollama takes 40 seconds just to tell  a joke. I have my other friends running ollama on windows on much slower cpu and it works much better. how to find out whats the issue, there is some issue here for sure.

**Comment by tak099** [comment]
How to increase the speed of the response?

**Comment by tak099** [comment]
<img width="805" alt="image" src="https://github.com/ollama/ollama/assets/143394573/255a4b10-a9c6-43c5-8fb1-5c5cdd8e99eb">
This is insane...

**Comment by OmarZidan1997** [comment]
Getting the same as people mentioning above. I bought intel laptop for $2.2k  with i7 13th gen, 32 gb ram. Takes ages to run simple command. I think it has to be with ubuntu being restricted from winOS to actually take controll most of the ram.  I am not ubuntu expert but wll make research on some configuration possibilities.

**Comment by protono** [comment]
`11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz`
`6.6.19-1-MANJARO`
`ollama server llama2 --verbose`
`>>> hello`
`total duration: 3.698377939s`

**Comment by OmarZidan1997** [comment]
> `11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz` `6.6.19-1-MANJARO` `ollama server llama2 --verbose` `>>> hello` `total duration: 3.698377939s`

Are you running on GPU or mainly CPU power?

**Comment by protono** [comment]
I'm using a lenovo t14 gen 2 laptop with irisx graphics.
