### ISSUE TITLE
More reliable model pull

### ISSUE THREAD

**Issue by bohdyone** [jmorganca/ollama#338]
Hi guys,

On Mac OS 13.4.1 and have been having some trouble downloading the larger models. 

I get occasional "unexpected EOF" issues and sometimes when the model is fully downloaded it is detected as corrupted and must be downloaded again. Some of this seems to be to do with system sleep interrupting the download, where it gets stuck and must be aborted and then resumed.

Is it possible to improve the reliability and resumability of downloads somewhat? 

Some suggestions:

1. Prevent system sleep (where possible) during model download
1. Use some sort of block-based hashing (e.g. Merkle tree) to detect corrupted blocks when resuming downloads

Thanks.

**Comment by mchiang0610** [comment]
@bohdyone Thanks for sending this in. We've been making background changes to this as we see the issues come. There is so much more to improve on the performance of downloading/uploading models on Ollama. Much more to come on this. 

Closing this issue for now since we are already making the changes. 

If you do see more, please try to give us the logs so we can troubleshoot. This will get improved overtime. 

Thank you so much for sending this in.
