### ISSUE TITLE
Where are the Modelfiles?

### ISSUE THREAD

**Issue by khromov** [jmorganca/ollama#359]
At some point the model files seem to have been located in the repo, such as this result which shows up on Google but now they are gone. Where can we find them? https://github.com/jmorganca/ollama/blob/main/library/modelfiles/llama2

**Comment by mchiang0610** [comment]
Hey @khromov, the default modelfiles are not gone, just that we haven't properly documented them yet. 

The modelfiles are used for us to provide the models, specific parameter settings, set prompts/system-prompts that the model authors recommend, and more. 

If you create your own modelfile, it'll layer on top of the 'base' modelfiles that we provide to ensure that the models provided are in a 'working' manner. Anything you specify in your modelfile can be used to override the provided default. For API users, it's great too since you can pass in your own prompts from scratch if needed. 

We've been moving pretty quickly, and just released a page to show all the models available for downloading: https://ollama.ai/library 

Haven't got to the readme yet for the models / showing default modelfiles or linking back to sources. Sorry about that.

**Comment by khromov** [comment]
Thanks! My goal was to check out the default settings and prompts that were used to tweak some things for existing models. Looking forward to the listing of the Modelfiles!

**Comment by mchiang0610** [comment]
Closing this for now since we will be adding readme soon. Happy to revisit this if that is insufficient. 

Thank you so much for submitting this. Appreciate it!
