### ISSUE TITLE
Different codellama models - confused

### ISSUE THREAD

**Issue by abulka** [jmorganca/ollama#449]
What is the difference between 
- ollama run codellama:7b 
- ollama run codellama:7b-instruct 
- ollama run codellama:7b-code

for general purpose (not python specialised) programming?

**Comment by mchiang0610** [comment]
@abulka sorry that it wasn't clear. 

- codellama:7b is the same as 7b-instruct, we alias it so that it'll be simple for people just wishing to run codellama. 

instruct is for general purpose - this is where you can just 'chat' or have a dialog with it. 

code - is made for code completion. So if you pass in partial unfinished code, it'll try to complete it. This is usually made for apps, code editors etc. 

Hope this helps! Let me know if I've answered your question, and how we can make it clear on the page. Did you find it in the Ollama model library?

**Comment by abulka** [comment]
Thanks for the explanation!  Would be useful if this info was added to https://ollama.ai/blog/run-code-llama-locally at least.

I'm subscribed to the Ollama newsletter and probably heard about it there - or possibly via the [TLDR newsletter](https://tldr.tech/changeset).

**Comment by technovangelist** [comment]
Hey there, the overview for the model on ollama.ai (https://ollama.ai/library/codellama) is the best place to go to find out, but I didn't make it easy to translate the name of the model variant to the actual tags. Now I have an example for each one.
![CleanShot 2023-09-01 at 09 57 01](https://github.com/jmorganca/ollama/assets/633681/f624e54d-02e1-49ed-990e-32ed12ad69fa)
