### ISSUE TITLE
Running a 70B Model with 16GB RAM: Possible Strategies?

### ISSUE THREAD

**Issue by OguzcanOzdemir** [jmorganca/ollama#467]
Hello,

I'm currently working with a system that has 16GB of RAM, and I'm interested in running a 70B model for my project. I understand that according to the GitHub repository's documentation, a 70B model typically requires 32GB of RAM.

However, due to my system limitations, I'm looking for guidance on potential strategies or alternative methods to run a 70B model efficiently with 16GB of RAM.

Are there any techniques, optimizations, or workarounds that I can explore to make this possible? I would greatly appreciate any advice or suggestions on how to approach this challenge and still achieve acceptable performance.

Thank you for your assistance and insights.

**Comment by ddkwork** [comment]
are you tested 70b？

**Comment by OguzcanOzdemir** [comment]
> are you tested 70b？

Yes I did. I got this message "Error: Post "http://127.0.0.1:11434/api/generate": EOF"

**Comment by technovangelist** [comment]
You got that message because you don't have enough memory. Unfortunately there isn't anything that can be done about that. You really have two strategies available. Use a cloud instance with enough memory, or upgrade to a machine with 64GB of memory. Anything below 64 and you are likely to see that kind of message. Why do you think you need a 70B model? For most cases, smaller models will suffice. Perhaps try some smaller models that will fit on your hardware. I will close this issue, since there is nothing that can be done on our side.

**Comment by OguzcanOzdemir** [comment]
> You got that message because you don't have enough memory. Unfortunately there isn't anything that can be done about that. You really have two strategies available. Use a cloud instance with enough memory, or upgrade to a machine with 64GB of memory. Anything below 64 and you are likely to see that kind of message. Why do you think you need a 70B model? For most cases, smaller models will suffice. Perhaps try some smaller models that will fit on your hardware. I will close this issue, since there is nothing that can be done on our side.

For some difficult questions, I thought the 70b model would provide more creative answers. Thanks for the answer. I will continue to use the 13b model.
