### ISSUE TITLE
Better Document /api/embeddings

### ISSUE THREAD

**Issue by FairyTail2000** [jmorganca/ollama#502]
It's currently not very clear on how to use is and how it's relation is to the EMBED Modelfile instruction.

Can you enlighten me and/or update the wiki and examples?

**Comment by saul-jb** [comment]
> It's currently not very clear on how to use is and how it's relation is to the EMBED Modelfile instruction.

I am only just learning about this myself but here is my findings.

The embedding is a way to convert generic content into a Vector representation (a list of numbers). This is useful because we can perform vector mathematics on these to compare them and how closely they relate together. You could compare a list of embeddings created from a long list of files to an embedding created from a prompt, then you could use the embedding the most closely matches and reverse lookup the file of relevance. This is essentially a semantic search.

The /api/embeddings will take a prompt and generate an embedding from it and return it to you. It is up to you to figure out what you want to do with it.

The EMBED Modelfile instruction appears create an embedding which allows it to use that data to when providing a result.

**Comment by FairyTail2000** [comment]
Thanks for your explanation. It makes sense now. Maybe @jmorganca can cover this in the documentation

**Comment by jmorganca** [comment]
Hi @FairyTail2000, for documentation on `/api/embeddings`, check out https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings

In terms of using these embeddings, check out [this guide](https://simonwillison.net/2023/Oct/23/embeddings) by @simonw which is a great guide on what embeddings are and how to use them.
