### ISSUE TITLE
416 response when pulling a model

### ISSUE THREAD

**Issue by codazoda** [jmorganca/ollama#528]
I'm getting the following error when I try to pull the lllama2-uncensored model.

```
$ollama pull llama2-uncensored
pulling manifest
Error: download failed: on download registry responded with code 416:
```

This might be a registry problem or a problem with the model I'm pulling. I'm not really sure the appropriate place to report the error. It's also entirely possible this is something to do with my internet connection, as I'm currently traveling.

Pulling llama2 works fine. Pulling llama2-uncensored:7b works fine (which should be the same thing, I think).

**Comment by BruceMacD** [comment]
This error (416) indicates that the resumable model download is trying to continue when the file is already fully downloaded. The download was probably corrupted by the unstable connection. To fix the problem in this case try updating to the most recent version of Ollama, it should purge the partially downloaded file and let you try again.

I'm going to leave this issue open because the error should be handled better than just blocking you from downloading.

**Comment by TahaScripts** [comment]
@BruceMacD could you point me to where the downloading is happening? I presume the error handling is within the `pull` function defined within [/main/api/client.py](https://github.com/jmorganca/ollama/blob/main/api/client.py); Seems like a good beginner contribution for me

**Comment by BruceMacD** [comment]
@TahaScripts 
The download is happening in `server/download.go`. The root issue here could be a bit tough, I think the solution will be doing checksums on smaller chunks while being the file is being downloaded.

**Comment by mchiang0610** [comment]
@codazoda thank you for creating this issue! This should be resolved. 

@TahaScripts Thank you for offering to help as well! Really appreciate it. We'll do more improvements on this to increase download/upload speeds to ollama library -- including the chunking
