### ISSUE TITLE
`ollama cp` followed by `ollama push` requires re-pushing layers

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#625]
To reproduce:

```
ollama cp llama2 <username>/llama2
ollama push <username>/llama2
```

**Comment by technovangelist** [comment]
so there are two possible ways to look at this. If i cp llama2 and try to push that, I have to repush the full model from scratch. But I have previously pushed mattw/shambler. I did a `ollama cp mattw/shambler mattw/testcpmodelshambler and pushed that and i didn't have to repush the layers. 

I seem to remember this was by design. Or is it?

**Comment by mxyng** [comment]
This is by design. copying a model does not inherit it in the same way as creating a model with `FROM`. If that's the desired behaviour, it should be considered an enhancement
