### ISSUE TITLE
Docs request: quantizations used for Llama models

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#643]
https://ollama.ai/library/llama2 is nice that it links the model sources as TheBloke.

Can we add what quantization is used?  That way there's more traceability as to what model is being run/downloaded.

---

Update: I can see from the aliases that it's Q4_0

![screenshot of aliases](https://github.com/jmorganca/ollama/assets/8990777/44411052-d333-4a9b-b513-4b9eed28394e)

I think though that's somewhat buried, it would be good to have a more explicit table explaining this.

**Comment by mchiang0610** [comment]
by default we use q4_0 for the models that we supply (subject to change if you're on the latest tag -- we'll try to pick one that's going to run well for the majority of users). 

Now, if you want to specifically pin a version that you want, you can directly use the tags, just like you'd do with containers: 

https://ollama.ai/library/llama2/tags 

we keep the aliases in there so that it's easier for new users to get started.

**Comment by jamesbraza** [comment]
Thanks for sharing about the Q4_0 model 👍 .

---

Looking at the `llama2:13b` tag:

<img width="297" alt="image" src="https://github.com/jmorganca/ollama/assets/8990777/348f831d-0d8c-49eb-9369-efe728566d45">

I believe this model corresponds with this: https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/blob/main/llama-2-13b-chat.ggmlv3.q4_0.bin (commit ID 56885c31d70174be02c72ce17904373df1d7830e).

However, I don't see how the commit ID in ollama.ai matches with the Hugging Face commit ID.

How can I go from commit ID to a model in Hugging Face?
