### ISSUE TITLE
Currently create is recrating whole model , how to just update?

### ISSUE THREAD

**Issue by v3ss0n** [jmorganca/ollama#726]
I am tuning pramaeters nad i have to re run `ollama create name modelfile` . That remake the model . If there is no model file changes can i just update the parameters?

**Comment by jmorganca** [comment]
Hi @v3ss0n, running `ollama create` still compares the integrity of the model as you build it to make sure nothing has changed (by calculating a checksum of the model). There isn't currently a way to speed this up, although we'll be looking into how to speed up the checksum algorithms with hardware at some point since that can be quite slow for large models. It shouldn't be taking longer than ~5-10 seconds. If it is, please let me know and I'll re-open this issue!
