### ISSUE TITLE
why different answers from same model?

### ISSUE THREAD

**Issue by Enhitech** [jmorganca/ollama#745]
Hi, guys,

I run a llama2 model and then access the model in three ways: 1. use rest api; 2. use cmd "ollama run modelname 'prompt'"; 3. use a conversational terminal.

I got different answers. 1 and 2 are similar, but 3 is much better than 1 and 2. 

WHY? how could I get the same answer as 3 via 1 or 2? 

Thanks a lot!

**Comment by SebJansen** [comment]
In 3, you probably entered multiple prompts, a sort of history

1 and 2, you only prompted once, which didn't create much of a context

**Comment by jmorganca** [comment]
Hi @Enhitech. Glad you tried Ollama! It's normal to get different responses from multiple calls. By default LLMs will output different answers due to randomness. To always get a consistent answer back, you get set `temperature: 0` and `seed: <seed value>` in the API.

Going to close this however feel free to re-open if something isn't working as expected
