### ISSUE TITLE
Support for Autogen

### ISSUE THREAD

**Issue by greg-peters** [jmorganca/ollama#754]
#305 Requesting support to use ollama with Autogen

**Comment by technovangelist** [comment]
It looks like Autogen would need to support calling ollama from them. Looks like there is an existing issue on their repo you could add your use case to: https://github.com/microsoft/autogen/issues/46

**Comment by MattBanak** [comment]
It's still _way_ too early to tell, but it seems more and more like the... "industry" (? can we use that term yet?) seems to be trending towards creating their LLM projects with APIs that tread OpenAI's GPT API as a spec so that smaller projects can be drop-in replacements.

Ollama _could_ decide to follow this trend, or you could use LiteLLM to fit the local models into that spec and keep going! More details in the thread linked on the "completed" status, but here's the last message describing how to do this: https://github.com/jmorganca/ollama/issues/305#issuecomment-1752150867

In my opinion, I think treating OpenAI's API as a spec is a good decision, and seems to be adopted more and more every day. I'm sure a unified spec will come out at some point, but for now that API seems to be the closest thing we have and plug-and-play compatibility is invaluable when technology is moving at the pace LLMs are.

**Comment by dlaliberte** [comment]
> It looks like Autogen would need to support calling ollama from them. Looks like there is an existing issue on their repo you could add your use case to: [microsoft/autogen#46](https://github.com/microsoft/autogen/issues/46)

Autogen supports a base_url config option, e.g. "base_url": "http://localhost:8000/v1", so no further change is needed by Autogen.   I'm using it now, but can't get anything useful out of Ollama. 

It appears Ollama's openai api support is lacking what AutoGen requires.  e.g. "/v1/chat/completions".  I can't tell what openai api support Ollama does have.  I only see "api/version" working.
