### ISSUE TITLE
interactive mode with prompt as argument

### ISSUE THREAD

**Issue by jonas-w** [jmorganca/ollama#820]
When passing a prompt as an argument e.g. `ollama run $MODEL "Hello World!"`, ollama will exit after this prompt and don't wait for further input, like it is with `ollama run $MODEL`.

Would it be possible to add an `-i` `--interactive` flag when passing the prompt directly?

**Comment by mchiang0610** [comment]
Hey @jonas-w Thank you for submitting this! I would love to understand your use case a little more. Possible to join our Discord? https://discord.gg/ollama 

Regarding the current behavior, it's made so that if you pass in an argument it'll complete it. For interactive mode, you can do `ollama run model`. Open to suggestions though. The reason why to not immediately add another `-i` or `--interactive` flag is because having so many flags in the future can make the project complicated to use. We should all as contributors keep the project simple. 

Thank you so much! And really open to suggestions.
