### ISSUE TITLE
Embed a UI with Ollama

### ISSUE THREAD

**Issue by coolaj86** [jmorganca/ollama#875]
Re: #874, https://github.com/ollama-webui/ollama-webui/pull/10

Once this next commit makes it into `ollama-webui` (which seems to be among the best of all the local ChatGPT UIs that I've found so far), it would be trivial to embed that interface directly into `ollama` so that it becomes more accessible to more people.

Using some `git tag` magic and a little other automation, this could be seamless and fool-proof to automate for releases.

**Comment by mchiang0610** [comment]
Hey @coolaj86 thank you for submitting this. Myself and many other maintainers on this project are huge fans of a great UI. For Ollama though, we are not specifically choosing to embed a UI for now because we want to support the many developers who are building their own UI. It would be unfair for Ollama to pick one and not support the others; they serve different use cases and users. What's amazing about an open-source community is giving users choice. Now, I do have to agree that in the future, we should maybe have something super simple to help users' troubleshoot / test. 

Here are some example UIs that are open source that I've found for Ollama: 

https://github.com/richawo/minimal-llm-ui
https://github.com/HelgeSverre/ollama-gui
https://github.com/jonathandale/chat-ollama
https://github.com/ivanfioravanti/chatbot-ollama
https://github.com/rtcfirefly/ollama-ui
https://github.com/ollama-webui/ollama-webui
https://github.com/ollama-interface/Ollama-Gui
https://github.com/ollama-ui/ollama-ui
https://github.com/Akintunde102/ollama-webui
https://github.com/FairyTail2000/ollama-frontend
https://github.com/ryanccn/ollama-web
https://github.com/nikhilPatilGit/ollama-ui
https://github.com/Frederick1989/Ollama-mistral-api-ui 
https://github.com/kghandour/Ollama-SwiftUI
https://github.com/rossuber/llm-chatter
https://github.com/mthongvanh/amallo
https://github.com/edwin-nz/ollama-chat
https://github.com/kacesensitive/ollama-twitch
https://github.com/musaubrian/olaf

CLI style UI: 
https://github.com/ggozad/oterm
